### ISSUE TITLE
Ember Easyform Compatibility

### ISSUE THREAD

**Issue by sir-dunxalot** [toranb/ember-cli-phone-number#1]
Hey dude,

The current setup of this addon doesn't enable easy integration with [Ember EasyForm](https://github.com/dockyard/ember-easyForm). It would be great to have an optional initializer or whatever that adds the phone number-formatting to EasyForm phone inputs. From a technical perspective this is not difficult. Given the widespread use of EasyForm, would you accept a PR for this? If so, I can go ahead and put up a PR.

**Comment by toranb** [comment]
Thanks for the issue ! I literally just built this to understand (better) how my team can share components. If you throw together a PR I'll give it a look (assuming it doesn't hinder people like me who don't use EasyForm I'd say it's a merge just waiting to happen).

Just a heads up - I'm working on a library that has _several_ of these handy UX helpers (in addition to phone number ... credit card stuff for MM/YY and credit card number /etc).

The moment I got this tested/working I realized it might be more valuable as a suite of these "mask" like components (is that appealing or would you/other devs _perfer_ to install a ton of these small mask components stand alone?)

Thanks again!

**Comment by sir-dunxalot** [comment]
Nice one! I like all of those suggestions. Personally, instead of installing lots of little helpers, I'd prefer an extendible solution that comes with a few 'premade' masking components whilst providing enough base classes and abstracted functionality to make it really easy to define custom masking for form elements. You could even write a blueprint to generate a new form mask.

I'll wait until you've got v1 of the suite of the helpers published and then I could add some EasyForm wrappers for them all if wanted - it wouldn't hinder non-EasyForm users in any way. Otherwise, there might be a simple way to implement them with EasyForm without adding to the core masking library.

**Comment by toranb** [comment]
Finally got around to writing the "one true masked addon"

https://github.com/toranb/ember-cli-masked-inputs

If you want to throw up a PR for Easyform compatibility that's cool :)

Also, I'd like to have a component in this lib for credit card number itself but realize it's not as simple as "mask one pattern" - if you know of another component that I could copy/ look at to see how this works I'd love to have it included in this addon

**Comment by sir-dunxalot** [comment]
Nice one! Thanks for following up. I'll check out the repo and think about how one might go about implementing it.

As for the credit card formatting, I've only use custom scripts in the past. Haven't come across a library but I'm sure there are some. I'll try and dig up the code I used in the past.
